### ISSUE TITLE
web 页面访问报错

### ISSUE THREAD

**Issue by yangkaiming666** [TarsCloud/TarsFramework#91]
**Error**
Looks like something broke!

        
SequelizeHostNotFoundError: getaddrinfo ENOTFOUND db.tars.com
    at /usr/local/app/web/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:127:19
    at tryCatcher (/usr/local/app/web/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/app/web/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/usr/local/app/web/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/usr/local/app/web/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/usr/local/app/web/node_modules/bluebird/js/release/promise.js:725:18)
    at _drainQueueStep (/usr/local/app/web/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/usr/local/app/web/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/usr/local/app/web/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/app/web/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:439:21)

**Comment by ruanshudong** [comment]
安装错了吧?
